### ISSUE TITLE
`npm run debug` attemps to create a symlink to the wrong path on Linux, Windows

### ISSUE THREAD

**Issue by ceuk** [KELiON/cerebro-plugin#1]
Just a heads up for people attempting to use the boilerplate on Windows/Linux. 

You'll need to change line `7` of [/scripts/debug](https://github.com/KELiON/cerebro-plugin/blob/master/scripts/debug)

On Ubuntu `symlink="${HOME}/.config/Cerebro/plugins/node_modules/${PWD##*/}"` works for me.

**Comment by KELiON** [comment]
@calvin-evans thanks for that! Can you do a PR with this fix to make it cross-platform? 

We can check platform using [this](http://stackoverflow.com/a/18434831/1087745) and set symlink path based on it. You can get platform paths from [electron documentation](https://github.com/electron/electron/blob/master/docs/api/app.md#appgetpathname) for `app.getPath` → `appData`

**Comment by mckennajones** [comment]
@KELiON 
Added support for Linux debugging, Windows is most likely not functional.
