### ISSUE TITLE
Dev tools and reload keyboard shortcuts don't seem to work on Linux/Windows

### ISSUE THREAD

**Issue by ceuk** [KELiON/cerebro-plugin#2]

**Comment by KELiON** [comment]
Looks like there is a global problem with hardcoded `cmd` button, but there is no cmd button on linux and windows:) Currently for dev. tools and reload you can turn on developer mode in settings and use tray menu → development

**Comment by KELiON** [comment]
After merging [this PR](https://github.com/KELiON/cerebro/pull/157) reload hotkey is not needed
